# Generated by Django 4.2.1 on 2023-05-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HumanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=5)),
                ('blood_type', models.CharField(max_length=5)),
                ('is_unemployed', models.BooleanField(default=False)),
                ('is_marriage', models.BooleanField(default=False)),
            ],
        ),
    ]
